### ISSUE TITLE
aggrid.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property

### ISSUE THREAD

**Issue by ghassen1khalil** [ag-grid/ag-grid-angular#231]
After doing `npm install --save ag-grid-angular ag-grid` and correctly adding `AgGridModule.withComponents([])` in my `AppModule` I get the following error when executing `npm start`

`ERROR in ./node_modules/ag-grid-angular/src/aggrid.module.ts
Module build failed: Error: /Users/ghassen/Desktop/workspace/flad/flad-front/flad-frontend/node_modules/ag-grid-angular/src/aggrid.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/ghassen/Desktop/workspace/flad/flad-front/flad-frontend/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:749:23)
    at plugin.done.then (/Users/ghassen/Desktop/workspace/flad/flad-front/flad-frontend/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ℹ ｢wdm｣: Failed to compile.
`

**Comment by ghassen1khalil** [comment]
I found a solution but I'm not sure if it's against how libraries should be packaged or not (as said [here](https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325) by@filipesilva) : 
`{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "include": [
    "../node_modules/ag-grid-angular/src/*.ts",
    "./main.ts",
    "./polyfills.ts"
  ],
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}`

**Comment by CristhianParra** [comment]
Go to your module and check that
`import { AgGridModule } from 'ag-grid-angular';`
is imported from root, not ag-grid-angular/*something*
